#!/usr/bin/env bash
filename=$1

if [ -e "$filename" ]; then
	if [ -f "$filename" ]; then
		echo "it is a file"
	elif [ -d "$filename" ]; then
		echo "it is a directory"
	else
		echo "not file or directory but exists"
	fi
else
	echo "file does not exist"
fi
