#!/usr/bin/env bash
filepath="$1"

if [ -e "$filepath" ]; then
	echo "$filepath passwords are enabled"
	if [ -w "$filepath" ]; then
		echo "you have the permission to edit the $filepath"
	else
		echo "you do NOT have the permission to edit the $filepath"
	fi
else
	echo "file does not exist"
fi
